package com.taobao.oceanbase.vo.inner;

public enum ObActionFlag {

	OP_USE_OB_SEM(1),
	OP_USE_DB_SEM(2),
	// OP_MH_FROZEN(3),
	// OP_MH_ACTIVE(4),
	OP_READ(5), 
	OP_UPDATE(6), 
	OP_INSERT(7),
	OP_DEL_ROW(8),
	OP_ROW_DOES_NOT_EXIST(11),

	BASIC_PARAM_FIELD(50),
	END_PARAM_FIELD(51), 
	TABLE_PARAM_FIELD(52),
	ROW_KEY_FIELD(53),
	TABLE_NAME_FIELD(54),
	COLUMN_PARAM_FIELD(55),
	SORT_PARAM_FIELD(56),
	LIMIT_PARAM_FIELD(57), 
	FILTER_PARAM_FIELD(58),
	MUTATOR_PARAM_FIELD(59),
	TABLET_RANGE_FIELD(60),
	OBDB_SEMANTIC_FIELD(61),
	GROUPBY_PARAM_FIELD(62),
	GROUPBY_GRO_COLUMN_FIELD(63),
	GROUPBY_RET_COLUMN_FIELD(64),
	GROUPBY_AGG_COLUMN_FIELD(65),
	UPDATE_COND_PARAM_FIELD(66),
	UPDATE_COND_FIELD(67),
	RESERVE_PARAM_FIELD(68);

	public long action;

	ObActionFlag(long action) {
		this.action = action;
	}

}