import os

env = Environment(
    CC = 'gcc',
    CXX = 'g++',
    LIBS = ['updateserver', 'common', 'tbsys', 'gtest', 'pthread', 'c', 'm', 'rt'],
    CCFLAGS = '-g -Wall -Werror -Wunused -Wno-deprecated -D__STDC_LIMIT_MACROS',
    CPPPATH = [os.environ['TBLIB_ROOT'] + '/include/tbsys', '..',
               '../common/', '../r8/', '../../oceanbase/dev/src/common',
               '../../updateserver', '..', '../..'],
    LIBPATH = [os.environ['TBLIB_ROOT'] + '/lib', '..', '../../updateserver'],
    )
#env.Library('btree', Glob('*.cpp'))
env.Program('test', Glob('test.cpp'))
env.Program('test1', ['test1.cpp'])
env.Program('test2', ['test2.cpp'])
env.Program('test3', ['test3.cpp'])
env.Program('test4', ['test4.cpp'])
