#!/usr/bin/env python2.6

###
### use to filter cases
### regression name: c,cp,j,jp,o,op
### Author: junyue

excludes=['bug217660_xiaochu', 'collect','trx_collect', 'ps_cache']

c_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'jdbc_ps_all_statement',
	'jdbc_replace',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','ps_lose_when','ps_lose_when2',
        'bind_variable_stress_greater_then_65535','bind_variable_stress_65535',
        ] + excludes

cp_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'jdbc_ps_all_statement',
        'special_hook',
        'set',
        'build_in_func_test',
        'kill',
        'killquery',
        'kill_index',
        'killquery_index',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
	'jdbc_replace',
	'jdbc_replace_trx',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','ps_lose_when','ps_lose_when2',
        'bind_variable_stress_65535','bind_variable_stress_greater_then_65535',
        ] + excludes

j_list=['ps_1',
        'ps_3',
        'select_error',
        'autocommit',
        'trx_1',
        'trx_2',
        'trx_3',
        'trx_4',
        'trx_5',
        'trx_basic',
        'empty_input',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'set',
        'serialize_6k_bug',
        'kill',
        'killquery',
        'kill_index',
        'killquery_index',
        'trx_timeout',
        'create_user',
        'create2',
        'scan_2M_size',
        'user_privilege',
        'user_pwd',
        'revoke',
        'session_timeout',
	'privileges',
	'jdbc_ps_all_statement',
        'query_method',
        'query_timeout',
	'sfu',
	'sfu2',
        'when_parallel1',
        'when_parallel3',
	'when_parallel2',
        'when_trx2',
        ] + excludes

jp_list=['ps_1',
        'ps_3',
        'select_error',
        'autocommit',
        'trx_1',
        'trx_2',
        'trx_3',
        'trx_4',
        'trx_5',
        'trx_basic',
        'empty_input',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'set',
        'many_columns',
        'build_in_func_test',
        'serialize_6k_bug',
        'kill',
        'killquery',
        'kill_index',
        'killquery_index',
        'trx_timeout',
        'create_user',
        'create2',
        'scan_2M_size',
        'user_privilege',
        'user_pwd',
        'revoke',
        'session_timeout',
	'privileges',
        'query_method',
        'query_timeout',
	'sfu',
	'sfu2',
        'when_parallel1',
        'when_parallel3',
	'when_parallel2',
	'when_trx2',
        ] + excludes

o_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'create_use',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
        'kill_index',
        'killquery_index',
	'set',
	'jdbc_replace',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'create_user',
        'trx_timeout',
        'session_timeout',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','jdbc_ps_all_statement','ps_lose_when','ps_lose_when2',
        'query_method',
        ] + excludes

op_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'build_in_func_test',
        'create_user',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
        'kill_index',
        'killquery_index',
	'set',
	'jdbc_replace',
	'jdbc_replace_parallel_trx',
        'create_user',
	'jdbc_replace_trx',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
        'trx_timeout',
        'session_timeout',
        'query_method',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','jdbc_ps_all_statement','ps_lose_when','ps_lose_when2',
        ] + excludes
