/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_mrsstable_SSTableBuilder */

#ifndef _Included_com_taobao_mrsstable_SSTableBuilder
#define _Included_com_taobao_mrsstable_SSTableBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_mrsstable_SSTableBuilder
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_mrsstable_SSTableBuilder_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_taobao_mrsstable_SSTableBuilder
 * Method:    append
 * Signature: (Ljava/nio/ByteBuffer;ZZZZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_taobao_mrsstable_SSTableBuilder_append
  (JNIEnv *, jobject, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_taobao_mrsstable_SSTableBuilder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_taobao_mrsstable_SSTableBuilder_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
